import type { Request, Response } from "express";
import { env } from "../config/env.js";
import { AppError } from "../errors/app-error.js";
import { beginGithubConnection, completeGithubConnection, convertGithubActivity, disconnectGithub, getGithubActivities, getGithubStatus, selectGithubRepositories, syncGithubActivities } from "../services/github-connection.service.js";
function owner(request: Request) { if (!request.auth?.userId) throw new AppError(401, "AUTHENTICATION_REQUIRED", "Authentication is required."); return request.auth.userId; }
export async function githubStatus(request: Request, response: Response) { response.json({ success: true, data: await getGithubStatus(owner(request)) }); }
export async function githubConnect(request: Request, response: Response) { const cookie = request.cookies?.[env.AUTH_COOKIE_NAME]; response.json({ success: true, data: await beginGithubConnection(owner(request), cookie) }); }
export async function githubCallback(request: Request, response: Response) { response.redirect(303, await completeGithubConnection(typeof request.query.state === "string" ? request.query.state : undefined, typeof request.query.installation_id === "string" ? request.query.installation_id : undefined, typeof request.query.code === "string" ? request.query.code : undefined, request.cookies?.[env.AUTH_COOKIE_NAME])); }
export async function githubDisconnect(request: Request, response: Response) { await disconnectGithub(owner(request)); response.json({ success: true, data: { disconnected: true } }); }
export async function githubRepositories(request: Request, response: Response) { response.json({ success: true, data: { connection: await selectGithubRepositories(owner(request), request.body.repositoryIds) } }); }
export async function githubSync(request: Request, response: Response) { response.json({ success: true, data: { activities: await syncGithubActivities(owner(request)) } }); }
export async function githubActivities(request: Request, response: Response) { const value = typeof request.query.kind === "string" ? request.query.kind : undefined; const kind = value === "commit" || value === "pull_request" || value === "release" ? value : undefined; const repositoryId = typeof request.query.repositoryId === "number" ? request.query.repositoryId : undefined; const page = typeof request.query.page === "number" ? request.query.page : 1; response.json({ success: true, data: { activities: await getGithubActivities(owner(request), kind, repositoryId, page), page } }); }
export async function githubConvertActivity(request: Request, response: Response) { const activityId = request.params.activityId; if (typeof activityId !== "string") throw new AppError(400, "VALIDATION_ERROR", "Invalid activity identifier."); response.json({ success: true, data: { signalId: await convertGithubActivity(owner(request), activityId) } }); }
